### ISSUE TITLE
Congratulations and question

### ISSUE THREAD

**Issue by frederikhors** [jultabary/4dk#4]
Congratulations for your project.

Can I ask you how to deal with db transactions calls?

**Comment by jultabary** [comment]
Hi thanks 😄 
You can implements your own `CommandBus` depending the framework you are using.
If you are in a SpringbootProjet : it can looks like something like this.
```
@Component
@Qualifier("transactionCommandBus")
public class TransactionCommandBus implements CommandBus {
         private CommandBus nextCommandBus;

         public TransactionCommandBus() {
         }
         
         @Transactionnal
         public List<Event> dispatch(Command command) {
                 return this.nextCommandBus.dispatch(command);
         }
         
         public void setNextCommandBus(CommandBus commandBus) {
                 this.nextCommandBus = commandBus;
         }
}
```
Then hen you will building the bus:
```
@Component
public class Application implements CommandBus, QueryBus {
       private CommandBus commandBus;
       private QueryBus queryBus;

       public Application(@Qualifier("transactionCommandBus") transactionCommandBus) {
            CommandBus commandDispatcher = new CommandDispatcher(.....);
            transactionCommandBus.setNextCommandBus(commandDispatcher);
            this.commandBus = transactionCommandBus;
            .....
      }

      public List<Event> dispatch(Command command) {
            return this.commandBus.dispatch(command);
      }
 
}

```
With a kind of commandBus like this all your "business" transaction (represents by CommandHandler) will be executed in a db transaction.


I will add an example in this repository.

**Comment by frederikhors** [comment]
Thank you. I'm using Rust. It would be awesome to have an example in Rust. :) ♥

**Comment by jultabary** [comment]
Have a look [here](https://github.com/jultabary/4dk/tree/main/rust/samples/complex-4dk-sample-integrated-with-rocket-and-sqlx) , i have updated this example with a new [command_bus](https://github.com/jultabary/4dk/blob/main/rust/samples/complex-4dk-sample-integrated-with-rocket-and-sqlx/src/infrastructure/persistence/persistence_middleware.rs) wich handle database transaction.

**Comment by jultabary** [comment]
By the way, it should better to wrap the persistence transaction middleware by the logging middleware. And not the opposite.
I will fix it later

**Comment by frederikhors** [comment]
> I will fix it later

Closed?

**Comment by jultabary** [comment]
Yes the sqlx rocket prject has been updated.
[here](urhttps://github.com/jultabary/4dk/blob/main/rust/samples/complex-4dk-sample-integrated-with-rocket-and-sqlx/src/main.rsl)

**Comment by frederikhors** [comment]
Thanks!
